package airtouch;

public enum MessageType {
    STANDARD_SEND,
    UNKNOWN, EXTENDED_SEND, STANDARD_RECEIVE, EXTENDED_RECEIVE, ZONE_CONTROL, ZONE_STATUS, AC_CONTROL, AC_STATUS, EXTENDED, AC_ERROR, AC_ABILITY, ZONE_NAME, CONSOLE_VERSION, CONTROL_OR_STATUS

}
